import type { Metadata } from "next";
import Script from "next/script";
// @ts-expect-error - the globals.css file is missing type definitions
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import { AuthProvider } from "@/utils/authProvider";
import { AvatarCacheProvider } from "@/utils/avatarCache";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="zh-Hant">
            <head>
                <Script
                    src="https://font.emtech.cc/emfont.js"
                    strategy="beforeInteractive"
                />
                <Script id="emfont-init" strategy="afterInteractive">
                    {`emfont.init();`}
                </Script>
            </head>
            <body className="emfont-NotoSansTC">
                <HeroUIProvider>
                    <AuthProvider>
                        <AvatarCacheProvider>
                            {children}
                        </AvatarCacheProvider>
                    </AuthProvider>
                </HeroUIProvider>
            </body>
        </html>
    );
}
